# Generated by Django 3.2 on 2025-06-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='name_not_me',
        ),
    ]
