# Generated by Django 3.2 on 2025-06-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20250531_1034'),
        ('reviews', '0001_create_review_and_comment_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='titles.title'),
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
